const PDT_ADMIN_MODULES = [
  {
    code: "DASHBOARD",
    name: "Dashboard",
    path: "/dashboard",
    icon: "FiGrid",
    navigationType: "SIDEBAR",
    isClickable: true,
    isVisible: true,
    sortOrder: 1,
    permissions: [
      { action: "READ", code: "DASHBOARD.READ", description: "View admin dashboard" },
    ],
  },
  {
    code: "RBAC",
    name: "RBAC",
    path: null,
    icon: "FiLock",
    navigationType: "SIDEBAR",
    isClickable: false,
    isVisible: true,
    sortOrder: 2,
    permissions: [],
  },
  {
    code: "USERS",
    parentCode: "RBAC",
    name: "Users",
    path: "/rbac/users",
    icon: "FiUsers",
    navigationType: "SIDEBAR",
    isClickable: true,
    isVisible: true,
    sortOrder: 3,
    permissions: ["READ", "WRITE", "UPDATE", "DELETE"].map((action) => ({
      action,
      code: `USERS.${action}`,
      description: `${action} users`,
    })),
  },
  {
    code: "ROLES",
    parentCode: "RBAC",
    name: "Roles",
    path: "/rbac/roles",
    icon: "FiShield",
    navigationType: "SIDEBAR",
    isClickable: true,
    isVisible: true,
    sortOrder: 4,
    permissions: ["READ", "WRITE", "UPDATE", "DELETE"].map((action) => ({
      action,
      code: `ROLES.${action}`,
      description: `${action} roles`,
    })),
  },
  {
    code: "MODULES",
    parentCode: "RBAC",
    name: "Modules",
    path: "/rbac/modules",
    icon: "FiBox",
    navigationType: "SIDEBAR",
    isClickable: true,
    isVisible: true,
    sortOrder: 5,
    permissions: ["READ", "WRITE", "UPDATE", "DELETE"].map((action) => ({
      action,
      code: `MODULES.${action}`,
      description: `${action} modules`,
    })),
  },
  {
    code: "AUDIT_LOGS",
    parentCode: "RBAC",
    name: "Audit Logs",
    path: "/rbac/audit-logs",
    icon: "FiActivity",
    navigationType: "SIDEBAR",
    isClickable: true,
    isVisible: true,
    sortOrder: 6,
    permissions: [
      { action: "READ", code: "AUDIT_LOGS.READ", description: "View audit logs" },
    ],
  },
];

const PDT_ADMIN_ROLES = [
  {
    code: "SUPER_ADMIN",
    name: "Super Admin",
    scope: "PLATFORM",
    permissions: ["*"],
  },
  {
    code: "ADMIN",
    name: "Admin",
    scope: "PLATFORM",
    permissions: [
      "DASHBOARD.READ",
      "USERS.READ",
      "USERS.UPDATE",
      "ROLES.READ",
      "ROLES.WRITE",
      "ROLES.UPDATE",
      "MODULES.READ",
      "MODULES.WRITE",
      "MODULES.UPDATE",
      "AUDIT_LOGS.READ",
    ],
  },
];

module.exports = {
  PDT_ADMIN_MODULES,
  PDT_ADMIN_ROLES,
};
